site-url: "http://unlimited.kptaipei.tw"
site-title: "野生柯P官網，你來打造"
site-name: "柯文哲野生官網 unlimited"
site-description: "以前有人說⋯⋯政府的網站很糟糕，設計得不夠好。所謂「官方」作的，不一定是最好、也不一定是市民想要的。甚至，對於什麼樣的網站才是「好」的，每個人也有不同的想像。因此，我們將市長候選人的網站開放，向市民徵求不同的想像、創意，自己來製作心目中理想的「官方網站」、無限個不一樣的柯文哲官方網站。"
og-type: "website"
og-image: "http://unlimited.kptaipei.tw/images/fb.png"
fb-admins: "612130717"

# Build settings
markdown: kramdown
